### ISSUE TITLE
Question: Aggressive expansion

### ISSUE THREAD

**Issue by davout1806** [crschnick/pdx_unlimiter#40]
I've been working on something that reads eu4 save files for a completely different purpose. I was wondering if you figured out how Aggressive Expansion was saved? I couldn't find anything online. I thought maybe in opinion_cache but if so I can't seem to figure it out.

Thanks.

**Comment by crschnick** [comment]
You can find aggressive expansion modifiers here:
countries -> <TAG> -> active_relations -> <other TAG> -> opinion -> any entry with modifier "aggressive_expansion".

I found that using the Pdx-Unlimiter editor by doing a quick search:
![image](https://user-images.githubusercontent.com/72509152/110649215-add0b080-81b9-11eb-9470-f28fe90025b2.png)

In the current version of the Pdx-Unlimiter, the editor that you can see above is disabled because I am reworking it.
If you are interested in using it to maybe locate other things in savegames as well, I can give you instructions on how to enable it if you want.
