### ISSUE TITLE
Mods marked as missing even though they're not (Option to reload mods or check them in the app)

### ISSUE THREAD

**Issue by yopiltzin** [crschnick/pdx_unlimiter#53]
Hello,
Thanks for the great tool here! I've loved it and I'm using it for EU4 currently. I've only had an issue regarding the mods loading in the savefile manager. The mod button in my current savefile is red, mentioning I'm missing 6 mods (all part of the Dynamic Themed Music collection); but I have them in my mod/ dir, as well can load them normally with both Irony and the PDX launcher.
I tried to:

-Uninstall and install the mods again with Steam
-Delete the mod/ folder so it gets created again by loading the PDX launcher
-And loading said campaign with the PDX launcher, to import it again in the PDX_Unlimiter app, with no success

I was wondering if there's anyway to make the PDX_Unlimiter to reload said mods or reload the savefile in order to make it work as intended. Thanks for the great work and keep it up! Let me know if I can be of help with this issue. Attached are images of the issue:
![bug1](https://user-images.githubusercontent.com/81983302/113602664-7e6e6180-9608-11eb-82f8-88235cdb9fb2.png)
![bug2](https://user-images.githubusercontent.com/81983302/113602682-829a7f00-9608-11eb-8f0f-9cdba313fa00.PNG)

**Comment by crschnick** [comment]
It seems like the Dynamic Cultured Music mods are in the legacy format, because the Steam Workshop version is still targeting 1.27.
The author providing download links to shady sites for newer versions seems a little fishy, so I wouldn't click on these links. (I did, would not recommend)

I will see what I can do to support the legacy mod format. Meanwhile, you can use the other launch options apart from Continue Game to start the Launcher and then manually enable the mods. Or alternatively just use the Continue Game button if you can live without the music.

**Comment by crschnick** [comment]
This problem should be fixed in the latest release that I just pushed

**Comment by yopiltzin** [comment]
Thank you! Checked some minutes ago, and it works perfectly. Thank you for the great tool!
