### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by yopiltzin** [crschnick/pdx_unlimiter#73]
Hey there! I'm trying to get back to using EU4 after a break, but my PDX-Unlimiter is not starting at all. It shows an error and quickly closes after that. I've managed to screenshot the error (attached). Even though it says the error is not terminal, I'm not able to use the app at all. I already tried uninstalling and reinstalling with no success. Thanks in advance!

![image](https://user-images.githubusercontent.com/81983302/142555907-e0182643-051e-43de-a1e9-717c3c99a63e.png)

**Comment by crschnick** [comment]
I have seen that issue a couple of times now over the last few months. It is caused by pdxu not being able to read the cached campaign flag images that are displayed for each campaign and savegame. I don't know how these images get corrupted sometimes, maybe a light defective hard drive or other issues. I had one case where a simple computer restart fixed the problem.

If a restart does not fix the problem for you, I can quickly create a build that lets you skip these errors.

**Comment by crschnick** [comment]
Also, a full log (located at `<user dir>\Pdx-Unlimiters\logs\<date>.log` or `<documents dir>\Pdx-Unlimiters\logs\<date>.log`) would be useful to know whether there are other problems as well.

**Comment by yopiltzin** [comment]
Hello! I erased the whole Pdx-Unlimiter folder in Documents/, reinstalled and it now works. I guess deleting the save games (which were from older versions so no longer usable for me) did the trick. Thanks!

**Comment by crschnick** [comment]
It was actually not about older versions being incompatible, it was about data not being read from your hard drive correctly.

I would recommend you to at least run a simple health check (e.g. as described [here](https://computing.which.co.uk/hc/en-gb/articles/115005587645-How-to-use-CHKDSK-Check-Disk-to-repair-a-hard-drive) ) just in case. If you find no issues, you can just attribute this occurrence to the hard drive having a bad day.
